FROM dhi.io/node:24.17.0-debian13-dev
LABEL maintainer="Mahesh <mahesh@ilimi.in>"
RUN apt-get update && apt-get install -y \
    python3 \
    make \
    g++ \
    libsnappy-dev \
    libsnappy1v5 \
    zip \
 && apt-get upgrade -y -o Dpkg::Options::="--force-confold" -o Dpkg::Options::="--force-confdef" \
 && rm -rf /var/lib/apt/lists/*
RUN mkdir -p /opt/telemetry
ADD src /opt/telemetry/
WORKDIR /opt/telemetry/
RUN npm ci --omit=dev
WORKDIR /opt
CMD ["zip", "-r", "telemetry-service.zip", "telemetry"]